FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY . .
RUN GOPROXY=https://goproxy.cn,direct go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./example/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"]